AWSTemplateFormatVersion: "2010-09-09"
Description: A CloudFormation template to deploy the Stable Diffusion Web UI by Automatic1111

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: sd-webui-sg
      GroupDescription: Security group for SD WebUI EC2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8188
          ToPort: 8188
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: g4dn.xlarge
      ImageId: ami-0574da719dca65348
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 100
            VolumeType: gp2
      "Tags": [{ "Key": "Name", "Value": "sd-web-ui-cf" }]
      SecurityGroups:
        - Ref: SecurityGroup
      UserData:
        "Fn::Base64": |
          #!/bin/bash
          cd /home/ubuntu
          git clone https://github.com/Detailing-the-Realm/comfyui-aws.git
          mv aws_comfyui_setup.sh/setup.sh ../
          bash aws_comfyui_setup.sh -y
          sudo sed -i "/#\$nrconf{restart} = 'i';/s/.*/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf
          sudo apt-get update
          sudo apt install wget git python3 python3-venv build-essential net-tools -y
          wget https://developer.download.nvidia.com/compute/cuda/12.0.0/local_installers/cuda_12.0.0_525.60.13_linux.run
          sudo sh cuda_12.0.0_525.60.13_linux.run --silent
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs
          sudo -u ubuntu git lfs install --skip-smudge
          # download the SD model v2.1 and move it to the SD model directory
          cd ComfyUI/models/checkpoints
          wget https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors
          wget https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors
          wget https://civitai.com/api/download/models/198962
          wget https://civitai.com/api/download/models/126688
          wget https://civitai.com/api/download/models/198530
          wget https://civitai.com/api/download/models/133832
          cd ../loras
          wget https://civitai.com/api/download/models/152042
          cd ../custom_nodes
          # change ownership of the web UI so that a regular user can start the server
          sudo chown -R ubuntu:ubuntu stable-diffusion-webui/

          # start the server as user 'ubuntu'
          sudo -u ubuntu nohup bash stable-diffusion-webui/webui.sh --listen > log.txt
  MyEIP:
    Type: AWS::EC2::EIP
  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      InstanceId: !Ref EC2Instance
